Fixed typo preventing using paid subscription key
This module worked fine with free keys but for my paid subscription key I got this error:
Exception: status 401: { "statusCode": 401, 
"message": "Access denied due to invalid subscription key. 
Make sure to provide a valid key for an active subscription." }
Changing "v1" by "v1.0" fixed it.